### PR TITLE
Parallelize for all linters

### PR DESCRIPTION
**Pull request by kftsehk**
Follow up #4088

## Proposed Changes

 since parallelizing should not lead to linter incompatibility, except for a non-deterministic order of files being linted

1. Shall all linter be parallelized by a standard script?
2. Possible to make parallelization out of experimental if passing all the test cases?

### Author/Contributor
- [ ] Implementation
- [ ] Tests
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by kftsehk** [comment]
you are right, there is no code yet, still thinking of how to best make it compatible with current implementation during free time.

I added to the title to [Do not merge] WIP in case any other get confused.

**Comment by ferrarimarco** [comment]
As part of this PR, can we please remove the experimental path added in #2920 ?

**Comment by ferrarimarco** [comment]
@kftsehk In #5041, I've changed how Gitleaks, textlint, and Jscpd run. Now, they run on the whole workspace instead of running one by one. In following PRs, I'll probably refactor more, probably starting from the ones you implemented experimental batch support for, so we can compare the two approaches.

In that PR, I'm also removing experimental batch support, so we can see how we can work on it in this PR, eventually for all linters.

Thanks a lot for pushing this effort!

**Comment by ferrarimarco** [comment]
To give you full context: this was prompted by Jscpd warning about duplicated code in the files that handled the experimental batch mode.

**Comment by kftsehk** [comment]
The main concern with linting whole WORKDIR, e.g. `eslint .` is breaking the "error count" of super-linter, which might not be desirable.

If such breaking change is acceptable, a lot of linter can simply call `<linter-name> "$GITHUB_WORKDIR"`

**Comment by ferrarimarco** [comment]
> The main concern with linting [the] whole WORKDIR, e.g. `eslint .` is breaking the "error count" of super-linter, which might not be desirable.

This is an interesting perspective. I wouldn't consider that change breaking though, because it's not part of the super-linter API. This can be improved in the future in the context of a new reporting feature if we have contributors willing to work on that particular reporting feature.

> If such breaking change is acceptable, a lot of linter can simply call `<linter-name> "$GITHUB_WORKDIR"`

#5041 adopts this approach for:

- jscpd, because looking for duplicates in files processing them one by one doesn't consider duplicates in other files, to it makes this linter way less effective, and it costs a lot in terms of overall performance.
- textlint, because it's based on plugins, and each plugin handles certain types of files. Also, textlint lets users specify custom extensions for a given file type in addition to the defaults. So, we let textlint handle this, instead of reimplementing the same logic. For example, with default plugins, textlint can lint `txt` and `md` files only, so there's no point in running it against all files one by one. If we/users install another textlint plugin, we don't need to modify any logic to handle an additional extension, nor custom extensions for any given plugin that users might have configured.
- Gitleaks, because we want to scan the whole workspace anyway.

This approach also has the added benefit of letting users rely on the file listing and ignoring logic of each linter, so their configuration becomes more portable if they decide to run the same linter by other means.

**Comment by ferrarimarco** [comment]
Also, I think that the approach I describe in my previous comment is not in contrast with your suggestion to run linters in parallel. They can happily work together!

**Comment by ferrarimarco** [comment]
After I rebased this PR, it got closed, sorry @kftsehk ! I'll see if I can reopen it.

**Comment by ferrarimarco** [comment]
I don't have access to your `parallel` branch anymore because the PR got closed.

As soon as you can push at least one commit there, the system should let me reopen this PR. Sorry for the confusion!

For context: the PR where you initially introduced the experimental parallel feature is #4088. May be useful to inspect the original implementation.

Thanks a lot for working on this!

**Comment by kftsehk** [comment]
sure, will update a bit later

**Pull request closed without merging**
