### PR TITLE
Adds latest write-good-rule dependency

### PR DESCRIPTION
**Pull request by gilacost**
Related to https://github.com/github/super-linter/pull/3554. 
**Summary**: Adds texlint write good rule so it can be used in a `.textlintrc`.

## Proposed Changes

* add [textlint-rule-write-good](https://www.npmjs.com/package/textlint-rule-write-good)

### CODE REVIEW

**Comment by gilacost** [comment]
@ferrarimarco ^^ 🙏

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Thanks for this new PR :)

Can you please add at least two tests (one `_good` (supposed to pass the check) and one `_bad` (supposed to fail the test)) that exercise this rule in `.automation/test/natural_language` ?

Thanks!

**Comment by gilacost** [comment]
Sure! I am happy to add them but I bear in mind that they wont run as this tests are run with the default template. 
This is how the default template should look like with this rule enabled:

```json
{
  "filters": {
    "comments": true
  },
  "rules": {
    "terminology": true,
    "write-good": true
  }
}
```

I do not think that this rule should be included as default, it is a bit strict and some times too much. 

### output example: 

```bash
❯ ./node_modules/.bin/textlint -c .textlintrc ./*

/Users/pepo/Repos/super-linter/.automation/test/natural_language/README.md
   7:4   error  "Additional" is wordy or unneeded  write-good
   7:27  error  "is needed" may be passive voice   write-good
  11:87  error  "successfully" can weaken meaning  write-good
  13:18  error  "are linted" may be passive voice  write-good
  19:18  error  "are linted" may be passive voice  write-good

/Users/pepo/Repos/super-linter/.automation/test/natural_language/natural_language_bad_01.md
  1:6   ✓ error  Incorrect usage of the term: “Javascript”, use “JavaScript” instead    terminology
  2:7   ✓ error  Incorrect usage of the term: “change logs”, use “changelogs” instead   terminology
  2:25  ✓ error  Incorrect usage of the term: “source-maps”, use “source maps” instead  terminology

/Users/pepo/Repos/super-linter/.automation/test/natural_language/natural_language_bad_02.md
  1:53  error  "it is" is wordy or unneeded      write-good
  1:56  error  "is needed" may be passive voice  write-good

✖ 10 problems (10 errors, 0 warnings)
✓ 3 fixable problems.
Try to run: $ textlint --fix [file]
```

This is why I think the dependency should be included but not as default. This would allow anyone interested to enable the rule by owerwriting the template.

Is there any way to overwrite for a particular test?

**Comment by ferrarimarco** [comment]
I see. Thanks for the details. Let's not add it in the default template. What happens if you instead add it in `.github/linters/.textlintrc` instead, so it runs for our own linting only?

**Comment by gilacost** [comment]
> I see. Thanks for the details. Let's not add it in the default template. What happens if you instead add it in `.github/linters/.textlintrc` instead, so it runs for our own linting only?

Let's see 😛

**Review by ferrarimarco — CHANGES_REQUESTED** [review]
Ok, at least we have some errors to fix, which is ok so we can use those to create failing tests.

From the output:

```
2023-01-16 11:44:38 [INFO]   File:[/tmp/lint/.automation/test/natural_language/README.md]
2023-01-16 11:44:38 [DEBUG]   Found errors. Error code: 1, File type: NATURAL_LANGUAGE, Error on missing exec bit: true
2023-01-16 11:44:38 [ERROR]   Found errors in [textlint] linter!
2023-01-16 11:44:38 [ERROR]   Error code: 1. Command output:
------

/tmp/lint/.automation/test/natural_language/README.md
   7:4   error  "Additional" is wordy or unneeded  write-good
   7:27  error  "is needed" may be passive voice   write-good
  11:87  error  "successfully" can weaken meaning  write-good
  13:18  error  "are linted" may be passive voice  write-good
  19:18  error  "are linted" may be passive voice  write-good

✖ 5 problems (5 errors, 0 warnings)
------
```

A couple of things to fix and we should be there:

1. Can you please fix the issues reported in the log?
2. Can you please add two new tests (one supposed to pass, one supposed to fail) for the `write-good` rule set?

Thanks!

**Comment by gilacost** [comment]
@ferrarimarco apologies for the late reply sir! ❤️

**Comment by gilacost** [comment]
Sorry guys but I am totally con fused by this [one](https://github.com/github/super-linter/actions/runs/3952163153/jobs/6779618330#step:7:243), I have autocrlf in my git config and my neovim config default encoding to  utf-8 :shrug:

**Comment by ferrarimarco** [comment]
I think that's because ansible-lint is reporting [this](https://github.com/github/super-linter/actions/runs/3952163153/jobs/6779618330#step:5:3746):

```
A new release of ansible-lint is available: 6.10.2 → 6.11.0 Upgrade by running: pip install --upgrade ansible-lint. Error code: 0
```

That string doesn't match the [regex we use to validate the version](https://github.com/github/super-linter/blob/main/test/inspec/super-linter/controls/super_linter.rb#L91):

```ruby
default_expected_stdout_regex = /(.*?)/s
```

The short term workaround would be to wait for the next round of dependency updates to be merged, although we might want to tune this regex (in a separate PR maybe?). @lindluni thoughts here?

**Comment by gilacost** [comment]
Any updates on this @ferrarimarco?

**Comment by lindluni** [comment]
Hi @gilacost 

I've finally gotten around to fixing the Ansible issues, can you rebase your change to resolve the conflict, then I'd be happy to work through this.

Thank you, and apologies for the delay

**Comment by gilacost** [comment]
> Hi @gilacost
> 
> I've finally gotten around to fixing the Ansible issues, can you rebase your change to resolve the conflict, then I'd be happy to work through this.
> 
> Thank you, and apologies for the delay

No worries! Done!

**Pull request closed without merging**
