### PR TITLE
Address pwsh install failure

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes https://github.com/super-linter/super-linter/issues/4887

## Proposed Changes

1. Open an issue upstream for the missing latest alpine release assets
2. Hard code latest version with alpine assets available

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by zkoppert** [comment]
Looks like we are no longer getting. a valid URL back from the GitHub Releases API. See https://github.com/super-linter/super-linter/actions/runs/6948319549/job/18904040786?pr=4888#step:6:3995

**Comment by zkoppert** [comment]
Tested the code change locally:

```bash
zkoppert@zacherys-mbp ~ % gh api repos/powershell/powershell/releases/tags/v7.3.10 | jq --arg target "x64" -r '.assets | .[] | select(.name | contains("linux-alpine-" + $target)) | .url'
https://api.github.com/repos/PowerShell/PowerShell/releases/assets/135884336
```

**Comment by zkoppert** [comment]
Running actions checks here since they dont seem to be kicking off normally: https://github.com/super-linter/super-linter/actions/runs/6948655973

**Comment by zkoppert** [comment]
This fix works! https://github.com/super-linter/super-linter/actions/runs/6948655973/job/18905093098#step:6:4002

We have already received an update though that will be better than this version pinning. https://github.com/PowerShell/PowerShell/issues/20746

I'll implement that now.... 🏃🏻

**Comment by ferrarimarco** [comment]
Nice!

**Pull request merged**
