### PR TITLE
Swift via swift-format

### LINKED ISSUE #127: Swift support
**Possible linters**

- [swiftlint](https://github.com/realm/SwiftLint) tool is widely using across swift community. 
- [swiftformat](https://github.com/nicklockwood/SwiftFormat) is also popular code formatting tool that have --lint option.

### PR DESCRIPTION
**Pull request by Gustl22**
Fixes #127

See also #535 

## Proposed Changes

1. Swift formatting and linting via [swift-format](https://github.com/apple/swift-format/)

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by Gustl22** [comment]
Installing lua failed, even for main branch: https://github.com/Gustl22/super-linter/actions/runs/5923607624/job/16060658552
Although it worked yesterday: https://github.com/Gustl22/super-linter/actions/runs/5920941915

Any ideas?

**Comment by Gustl22** [comment]
Swift cannot compiled on Docker Alpine anatively: https://forums.swift.org/t/porting-to-musl-was-building-static-binaries-reducing-library-dependencies/808

**Comment by Gustl22** [comment]
Using https://github.com/mtgto/docker-swift-format/tree/main in the meantime, which is available for Ubuntu images.

**Comment by Gustl22** [comment]
Musl / Alpine seems to get pushed: https://github.com/apple/swift/pull/62245
Let's hope it's there soon :)

**Comment by Gustl22** [comment]
Hmm, I can't continue without the alpin image, but would be kind of waste to close it (and start from scratch cause noone noticed). The alpin image should be available sooner or later, I think.

**Comment by ferrarimarco** [comment]
This is blocked by https://github.com/apple/swift/pull/62245

**Comment by ferrarimarco** [comment]
Closing this one. We can reopen once the alpine image is available.

**Pull request closed without merging**
