### PR TITLE
Add exact version number to action.yml on release

### LINKED ISSUE #4650: version pinning needs to be exact?
Isn't that behaviour potentially unexpected? When I pin super-linter/slim to v5.2.2, it'll fetch the slim-v5 image, which is going to be some more recent version than v5.2.2 in the future, no?

_Originally posted by @bewuethr in https://github.com/super-linter/super-linter/issues/4564#issuecomment-1716147164_

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes #4650

## Proposed Changes

1. Update action.yml and slim/action.yml with exact version numbers just before tagging a release.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by Hanse00** [comment]
Just to ensure I understand this change correct:

Each time we execute the release workflow (Thereby, building a new ghcr image), two automated git commits will be pushed to main, updating these two files: https://github.com/super-linter/super-linter/blob/main/action.yml, https://github.com/super-linter/super-linter/blob/main/slim/action.yml with the fully qualified image name of the newest container image.

The purpose of that, is to ensure that anyone using the GitHub Action in their own workflows, always has access to the latest super-linter container in their workflows.

Is that correct?

**Comment by zkoppert** [comment]
@Hanse00 Yes that is correct

**Review by Hanse00 — APPROVED** [review]

**Comment by zkoppert** [comment]
The workflow failure seems to be coming from [403 returns from the API](https://github.com/super-linter/super-linter/actions/runs/6410181832/job/17402919697?pr=4694#step:6:2945). I'll have to find some time to dig deeper into why this is happening.

**Comment by zkoppert** [comment]
closing as duplicate of https://github.com/super-linter/super-linter/pull/4733

**Pull request closed without merging**
