### PR TITLE
Add Babel preset for React package

### PR DESCRIPTION
**Pull request by fdanielsen**
The React preset for Babel is useful for automatically adding Babel plugins to understand JSX syntax.

## Proposed Changes

1. Add Babel preset for React
2. Update Babel ESLint parser to new package name

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by zkoppert** [comment]
@fdanielsen Thanks for submitting a pull request! 

I'm confused and need some help to determine what we are trying to accomplish here. This pull request currently adds a dependency but then I don't see any code that actually uses that dependency. Can you help me understand the goal of this pull request?

**Comment by zkoppert** [comment]
That makes more sense. Can you resolve the branch conflicts and we can get this one merged through?

**Comment by fdanielsen** [comment]
Great, I've merged in latest from the main branch now and fixed conflicts.

**Review by zkoppert — APPROVED** [review]
🎉 Thanks for the contribution!!

**Comment by fdanielsen** [comment]
> 🎉 Thanks for the contribution!!

Thanks for the prompt review! Any idea when you'll make a new release so I can test this out in a GitHub action?

**Comment by zkoppert** [comment]
I try to keep an every Friday release schedule but am also terrible at doing it consistently. So, i've just published a new release so you can give it a try anytime.

https://github.com/super-linter/super-linter/releases/tag/v5.3.1

**Pull request merged**
