### PR TITLE
use checkout v4 in README

### PR DESCRIPTION
**Pull request by zkoppert**
Fixes #

## Proposed Changes

1. Update documentation to reference the latest version of actions/checkout

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [x] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by massongit** [comment]
https://github.com/super-linter/super-linter/blob/cb28d4d99196152f8b6f51c83caf53deb642bdd9/docs/run-linter-locally.md?plain=1#L91

I think it is better to update the above as well.

**Comment by massongit** [comment]
https://github.com/super-linter/super-linter/blob/cb28d4d99196152f8b6f51c83caf53deb642bdd9/.github/workflows/ci.yml#L26

I think it is a good idea to update the `actions/checkout` version in ci to ensure the `README.md` description.

**Comment by zkoppert** [comment]
> https://github.com/super-linter/super-linter/blob/cb28d4d99196152f8b6f51c83caf53deb642bdd9/.github/workflows/ci.yml#L26
> 
> I think it is a good idea to update the `actions/checkout` version in ci to ensure the `README.md` description.

I've got that covered in another PR

**Comment by zkoppert** [comment]
> https://github.com/super-linter/super-linter/blob/cb28d4d99196152f8b6f51c83caf53deb642bdd9/docs/run-linter-locally.md?plain=1#L91

Thanks for catching that! I've just added a commit to cover that one.

**Pull request merged**
