### PR TITLE
chore: Add `.DS_Store` to `.gitignore`

### PR DESCRIPTION
**Pull request by holtskinner**
## Readiness checklist

In order to have this pull request merged, complete the following tasks.

### Pull request author tasks

- [X] I checked that all workflows return a success.
- [X] I included all the needed documentation for this change.
- [X] I provided the necessary tests.
- [X] I squashed all the commits into a single commit.
- [X] I followed the
      [Conventional Commit v1.0.0 spec](https://www.conventionalcommits.org/en/v1.0.0/).
- [X] I wrote the necessary upgrade instructions in the
      [upgrade guide](../docs/upgrade-guide.md).
- [X] If this pull request is about and existing issue, I added the
      `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` text to the description of
      the pull request.

### Super-linter maintainer tasks

- [x] Label as `breaking` if this change breaks compatibility with the previous
      released version.
- [x] Label as either: `automation`, `bug`, `documentation`, `enhancement`,
      `infrastructure`.
- [x] Add the pull request to a milestone, eventually creating one, that matches
      with the version that release-please proposes in the
      `preview-release-notes` CI job.

### CODE REVIEW

**Review by ferrarimarco — APPROVED** [review]

**Comment by ferrarimarco** [comment]
Thanks for this PR!

**Comment by ferrarimarco** [comment]
Can you please refactor the commit message? What you used as the PR title should be fine. Thanks!

```
Add .DS_Store to .gitignore (#6241)
  ✖   subject may not be empty [subject-empty]
  ✖   type may not be empty [type-empty]
```

**Comment by holtskinner** [comment]
I think I fixed it

**Review by ferrarimarco — APPROVED** [review]
Yes, thanks!

**Pull request merged**
