### PR TITLE
Add dependencies for Next (node), React (node), and Standard (ruby)

### PR DESCRIPTION
**Pull request by ChrisPage-AT**
Fixes #

As stated in https://github.com/super-linter/super-linter/issues/4349, I am trying to lint some repositories that have dependencies that aren't included in the super-linter image. Since there does not appear to be a way to add those dependencies at the time of pipeline run, I've done my best to add them here.

@zkoppert sorry for targeting the wrong repo in https://github.com/github/super-linter/pull/3.

## Proposed Changes

1. Adding the standard gem to the ruby dependencies
2. Adding the next package to the node dependencies
3. Adding the react package to the node dependencies

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by zkoppert** [comment]
👋🏻 @ChrisPage-AT It looks like the files changed tab has no changes for this PR. Are your changes already merged somehow?

**Comment by ChrisPage-AT** [comment]
> 👋🏻 @ChrisPage-AT It looks like the files changed tab has no changes for this PR. I see in the commits that your changes were reverted in following commits. Was that intentional?

Sorry, I thought I had merged my changes back to my local main.  Changes should be in there now.

**Comment by zkoppert** [comment]
Looks like the build fails with

> > [base_image  4/39] RUN npm install && chown -R "$(id -u)":"$(id -g)" node_modules && bundle install:
6.471 npm ERR! Fix the upstream dependency conflict, or retry
6.471 npm ERR! this command with --force or --legacy-peer-deps

**Comment by zkoppert** [comment]
Looks like this issue is on main branch as well. I'll work on fixing that and then come back here to rebase.

**Comment by zkoppert** [comment]
Oh boy. Ok going to try to break this up into 3 prs. one for each dependency to add.

**Comment by zkoppert** [comment]
starting here: https://github.com/super-linter/super-linter/pull/4503

**Comment by zkoppert** [comment]
Tried this a couple different ways and ended up in dependency conflicts. If you are able to resolve the version conflicts then we can get this one through.

**Comment by ChrisPage-AT** [comment]
@zkoppert I think I've updated everything that needs it.  The only big change is that the standard ruby gem requires rubocop version 1.48.1 instead of 1.54.1.

**Comment by ChrisPage-AT** [comment]
@zkoppert it looks like the builds are failing with:
`ERROR! Failed to call GitHub Status API!
ERROR:[curl: (22) The requested URL returned error: 403]`
Do you know if this is related to my changes, or a different issue?

**Comment by zkoppert** [comment]
I believe that is a different issue. I'll rerun the action.

**Comment by zkoppert** [comment]
The slim on reran and errored here: https://github.com/super-linter/super-linter/actions/runs/5715565427/job/15527488337?pr=4446#step:6:1973

**Review by zkoppert — APPROVED** [review]

**Pull request merged**
